# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Thomas J. Hils
tagline:          Human Being
url:              http://tjhils.github.io
paginate:         1
baseurl:          /
author:
  name:           Thomas Hils
  url:            https://twitter.com/tjhils
  email:          thomas@hils.us

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/tjhils/tjhils.github.io
