# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            words.md
tagline:          'automating myself out of a job'
description:      ''
url:              http://tjhils.github.io
baseurl:          /

author:
  name:           'Thomas Hils'
  url:            https://twitter.com/tjhils

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tjhils/tjhils.github.io

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'


# Twitter

twitter:
  consumer_key: asdf
  consumer_secret: asdf
  access_token: asdf
  access_token_secret: asdf