# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Thomas J. Hils
tagline:          'Human Being'
description:      'A blog about nothing.'
url:              http://tjhils.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Custom vars
version:          1.0.0

github:
  repo:           http://tjhils.github.io
