# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems: 			  [jekyll-paginate]

# Permalinks
permalink:        pretty


# Setup
title:            i made the things
tagline:          
description:      
url:              http://things.imade.today
baseurl:          /

author:
  name:           'Zap Zaplar'
  url:            https://twitter.com/zapiertest

paginate:         5

# Custom vars
version:          2.1.0

# github:
#  repo:           https://github.com/tjhils/tjhils.github.io

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

exclude: [s3_website.yml]
