# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            tjhils
tagline:          'words.md'
description:      ''
url:              http://tjhils.github.io
baseurl:          /

author:
  name:           'Thomas J. Hils'
  url:            https://twitter.com/tjhils

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tjhils/tjhils.github.io

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'